version: '3'
services:
  mongo:
    container_name: dungeon-scheduler-mongo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dungeon-scheduler
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminPassword
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
